### ISSUE TITLE
Make server port queryable

### ISSUE THREAD

**Issue by pniederw** [lantunes/fixd#31]
In most cases, a server fixture shouldn't run on a fixed port, as there is no guarantee that any particular port is unused at a given time (think CI server). Instead, a free port should be chosen automatically, which can be achieved by passing 0 as the port number. However, what seems to be missing is a way to query the actual port, so that clients know which port to connect to.

**Comment by lantunes** [comment]
Hi, thanks for the suggestion. This is a very important point. I apologize for having been away from this project for so long, and thanks for your interest in it. I will try to get this implemented and released within the next week.

**Comment by lantunes** [comment]
This has been implemented in version 1.0.3, released today.
